/**
 * The YouTube demos, in one place so the <VideoShowcase /> section and the
 * VideoObject structured data in <JsonLd /> can never drift apart.
 *
 * Titles, descriptions, durations, and upload dates are taken verbatim from
 * YouTube (oEmbed + the watch page's own metadata) — nothing here is invented.
 * `description` is what ships in the schema.org payload. The site-voice
 * caption and the mono tag live in the i18n dictionaries, keyed by video id,
 * because those are ours to translate while everything here is not.
 */
export type Video = {
  /** YouTube video id. */
  id: string;
  /** Verbatim YouTube title. */
  title: string;
  /** Schema.org description — faithful to the real YouTube description. */
  description: string;
  /** ISO 8601 duration. */
  duration: string;
  /** Human duration for the badge. */
  runtime: string;
  /** ISO 8601 upload date, straight from the watch page. */
  uploadDate: string;
  /** Set when the video demos something not in a stable release yet. */
  preview?: boolean;
};

export const VIDEOS: Video[] = [
  {
    id: "YWzD3-xkCEc",
    title: "World's best Linux Wallpaper app Fresco, has Pinterest Link support!",
    description:
      "Paste Pinterest Link into this Linux app and set it as your Wallpaper.",
    duration: "PT45S",
    runtime: "0:45",
    uploadDate: "2026-07-22T12:42:41-07:00",
  },
  {
    id: "C1MqrhGkovQ",
    title: "I Added Live Song Lyrics Widgets to Linux Desktop | Fresco",
    description:
      "Your Linux desktop just got a lot more enjoyable. An upcoming Fresco feature: live synchronized song lyrics as desktop widgets, along with a new clock widget. Whether you're coding, studying, or just listening to music, your lyrics stay on your desktop without needing to keep another window open. Lightweight, works over animated wallpapers, and supports both Wayland and X11.",
    duration: "PT30S",
    runtime: "0:30",
    uploadDate: "2026-07-28T21:25:50-07:00",
  },
];

/** Poster art. maxresdefault is confirmed present for both ids. */
export const posterUrl = (id: string) =>
  `https://i.ytimg.com/vi/${id}/maxresdefault.jpg`;

/** Fallback poster, always generated by YouTube for every video. */
export const fallbackPosterUrl = (id: string) =>
  `https://i.ytimg.com/vi/${id}/hqdefault.jpg`;

export const watchUrl = (id: string) =>
  `https://www.youtube.com/watch?v=${id}`;

/** Privacy-preserving embed host — no cookies until the viewer plays. */
export const embedUrl = (id: string) =>
  `https://www.youtube-nocookie.com/embed/${id}`;

export const CHANNEL_URL = "https://www.youtube.com/@dibbayajyotiroy7399";
